# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('coddpto', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombredpto', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='supermercados',
            fields=[
                ('codsuper', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombresuper', models.CharField(max_length=40)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='codsuper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAprende.supermercados'),
        ),
    ]
