# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAprende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('codproducto', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField(max_length=200)),
                ('marca', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagenes')),
                ('tipo', models.CharField(max_length=60)),
                ('tamano', models.CharField(choices=[('Peque\xf1o', 'Peque\xf1o'), ('Mediano', 'Mediano'), ('Grande', 'Grande'), ('Extra', 'Extra')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('coddpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAprende.departamentos')),
            ],
        ),
    ]
