# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAprende', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('codoferta', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('codproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAprende.productos')),
            ],
        ),
    ]
