# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAprende', '0003_ofertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
